#!/bin/bash
set -x

LOCAL_DATA_DIR="$HOME/owncloud/mysql-data"       #Select directory to mount for persisting mysql database

[ ! -d "$LOCAL_DATA_DIR" ] && mkdir -p "$LOCAL_DATA_DIR"
# Persistent database version
docker run -d -p 3306:3306 -v "$LOCAL_DATA_DIR":/var/lib/mysql --name oc-mysql owncloud-mysql

#docker run -d -p 3306:3306 --name oc-mysql owncloud-mysql
docker run -d -p 80:80 --name oc --link oc-mysql:oc-mysql -v /home/bene/owncloud/data:/data owncloud

# Run interactive
# Image should run cmd /bin/bash
# docker run -ti -p 80:80 --name oc --link oc-mysql:oc-mysql -v /home/bene/data:/data owncloud
